import { Link } from 'wouter';
import { ChevronLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { BottomNav } from '@/components/BottomNav';

export function TermsOfService() {
  return (
    <div className="min-h-screen bg-background pb-24">
      <div className="px-4 pt-6 pb-4 max-w-2xl mx-auto">
        <div className="flex items-center gap-3 mb-6">
          <Link href="/">
            <Button variant="ghost" size="icon">
              <ChevronLeft className="w-5 h-5" />
            </Button>
          </Link>
          <div>
            <h1 className="text-2xl font-bold font-display">Terms of Service</h1>
            <p className="text-sm text-muted-foreground">Last updated: May 19, 2026</p>
          </div>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-sm text-muted-foreground leading-relaxed">

          <section>
            <p className="text-foreground font-medium p-4 bg-yellow-500/10 border border-yellow-500/20 rounded-xl">
              ⚠️ IMPORTANT: By using RAIMZEAL you confirm you are at least 18 years of age and agree to these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">1. Acceptance of Terms</h2>
            <p>These Terms of Service ("Terms") govern your use of the RAIMZEAL fitness application and website at raimzeal.com (the "Service"), operated by RAIMZEAL ("we", "us", or "our"). By creating an account, downloading the app, or accessing any part of the Service, you agree to be bound by these Terms and our Privacy Policy. If you are accessing the Service on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">2. Eligibility &amp; Age Requirement</h2>
            <p>You must be at least <strong className="text-foreground">18 years of age</strong> to use RAIMZEAL. By registering, you represent and warrant that you are 18 or older. We reserve the right to terminate accounts of users found to be under 18. This Service is not directed to persons under 18 and we do not knowingly collect data from minors.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">3. Medical Disclaimer &amp; Personal Responsibility Waiver</h2>
            <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-xl space-y-2">
              <p><strong className="text-foreground">RAIMZEAL IS NOT A MEDICAL DEVICE AND DOES NOT PROVIDE MEDICAL ADVICE.</strong></p>
              <p>All content, AI coaching responses (Ovia AI), workout plans, nutrition guidance, and health information provided through RAIMZEAL are for informational and educational purposes only. They are <strong className="text-foreground">not a substitute for professional medical advice, diagnosis, or treatment.</strong></p>
              <p>By using RAIMZEAL, you expressly acknowledge and agree that:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>You assume full personal responsibility for your physical activity, dietary choices, and health decisions.</li>
                <li>Exercise carries inherent risk of injury. You participate in all workouts and physical activities at your own risk.</li>
                <li>You should consult a qualified physician or healthcare professional before beginning any new exercise programme, diet, or supplement regime — especially if you have any pre-existing medical conditions.</li>
                <li>Ovia AI responses are generated by artificial intelligence and may not be accurate or appropriate for your specific situation. Always verify AI-generated health advice with a qualified professional.</li>
                <li>RAIMZEAL, its owners, employees, and affiliates shall not be liable for any injury, illness, loss, or damage arising from your use of the Service or reliance on any content therein.</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">4. Account Registration &amp; Security</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must provide accurate, current, and complete information during registration.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</li>
              <li>You must notify us immediately at support@raimzeal.com of any unauthorised use of your account.</li>
              <li>You may not share your account with any other person or allow others to access the Service through your account.</li>
              <li>We reserve the right to refuse registration or cancel accounts at our sole discretion.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">5. Membership Plans &amp; Billing</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-foreground">Foundation (Free):</strong> includes limited access to workout library, basic nutrition tracking, read-only community access, and limited Ovia AI coaching.</li>
              <li><strong className="text-foreground">Athlete ($9.99/month):</strong> includes full workout library and programs, unlimited nutrition logging, body measurements, unlimited Ovia AI, community posting, progress PDF export, activity tracker, reminders, and calendar scheduling.</li>
              <li><strong className="text-foreground">Elite ($19.99/month):</strong> includes all Athlete features plus priority AI responses, AI meal planning, custom workout builder, coaching digests, and Elite badge.</li>
              <li>Annual plans are available at a discounted rate.</li>
              <li>All payments are processed by Stripe, Inc. By subscribing, you authorise us to charge your payment method on a recurring basis.</li>
              <li>Subscriptions automatically renew at the end of each billing period unless you cancel before the renewal date via Settings → Manage Subscription.</li>
              <li><strong className="text-foreground">Cancellation:</strong> you may cancel at any time. Access continues until the end of the current billing period. No refunds are issued for partial billing periods except where required by law.</li>
              <li>Prices may change with 30 days' advance notice. Continued use after a price change constitutes acceptance of the new price.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">6. Ovia AI — Artificial Intelligence Coaching</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Ovia AI is powered by OpenAI's GPT-4.1 language model and is designed exclusively for fitness, nutrition, and wellness guidance.</li>
              <li>Ovia AI is <strong className="text-foreground">not a licensed medical professional, therapist, or dietitian.</strong></li>
              <li>AI responses may occasionally contain errors, outdated information, or advice that is not appropriate for your individual circumstances. Always apply critical judgement and consult a professional where appropriate.</li>
              <li>You may not use Ovia AI to seek advice for medical emergencies. In an emergency, call your local emergency services immediately.</li>
              <li>We may implement usage limits on Ovia AI based on your membership plan.</li>
              <li>We reserve the right to log AI conversations for safety, quality improvement, and compliance purposes, subject to our Privacy Policy.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">7. Community Guidelines</h2>
            <p>The RAIMZEAL community feed is a positive space for fitness motivation and support. You agree not to post content that:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Is abusive, harassing, defamatory, threatening, or hateful.</li>
              <li>Promotes dangerous or extreme dieting, disordered eating, or harmful fitness practices.</li>
              <li>Contains nudity, graphic content, or sexual material.</li>
              <li>Infringes any copyright, trademark, or intellectual property right.</li>
              <li>Constitutes spam, advertising, or unsolicited promotion of third-party products.</li>
              <li>Contains false medical or health claims.</li>
              <li>Violates any applicable law or regulation.</li>
            </ul>
            <p className="mt-2">We reserve the right to remove content and suspend or terminate accounts that violate these guidelines without notice.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">8. Intellectual Property</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>The RAIMZEAL name, logo, app design, workout content, and all related materials are the intellectual property of RAIMZEAL and are protected by copyright, trademark, and other applicable laws.</li>
              <li>You may not copy, modify, distribute, sell, or create derivative works from our content without express written permission.</li>
              <li>You retain ownership of content you create and post (progress photos, community posts). By posting, you grant us a non-exclusive, royalty-free, worldwide licence to display and distribute your content within the Service.</li>
              <li>You represent that you own or have the rights to any content you post.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">9. Prohibited Uses</h2>
            <p>You may not use the Service to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Reverse engineer, decompile, or disassemble any part of the Service.</li>
              <li>Attempt to gain unauthorised access to any part of our systems or another user's account.</li>
              <li>Use automated bots or scripts to scrape data or abuse our API.</li>
              <li>Interfere with the security or integrity of the Service.</li>
              <li>Violate any applicable local, national, or international law or regulation.</li>
              <li>Circumvent or bypass any subscription enforcement or access controls.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">10. Disclaimers &amp; Limitation of Liability</h2>
            <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>
            <p className="mt-2">TO THE MAXIMUM EXTENT PERMITTED BY LAW, RAIMZEAL SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, PERSONAL INJURY, PROPERTY DAMAGE, OR LOST PROFITS, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.</p>
            <p className="mt-2">OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">11. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless RAIMZEAL and its officers, directors, employees, and agents from and against any claims, damages, losses, costs, and expenses (including reasonable attorneys' fees) arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party right; or (d) any content you submit to the Service.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">12. Termination</h2>
            <p>We reserve the right to suspend or terminate your account at any time, with or without cause or notice, including if we believe you have violated these Terms. Upon termination, your right to use the Service ceases immediately. You may also delete your account at any time via Settings. Provisions that by their nature should survive termination (including disclaimers, limitation of liability, and indemnification) shall survive.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">13. Governing Law &amp; Disputes</h2>
            <p>These Terms are governed by the laws of the Federal Republic of Nigeria, without regard to conflict of law principles. Any disputes arising from these Terms or your use of the Service shall first be attempted to be resolved through good-faith negotiation. If unresolved, disputes shall be submitted to the courts of competent jurisdiction in Nigeria.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">14. Changes to Terms</h2>
            <p>We may modify these Terms at any time. Material changes will be notified via email or in-app notice at least 7 days before taking effect. Continued use of the Service after changes take effect constitutes acceptance. If you do not agree to updated Terms, you must stop using the Service and may delete your account.</p>
          </section>

          <section>
            <h2 className="text-foreground font-semibold text-base mb-2">15. Contact</h2>
            <div className="p-4 bg-card border border-border rounded-xl">
              <p className="text-foreground font-semibold">RAIMZEAL</p>
              <p>Email: <strong className="text-foreground">support@raimzeal.com</strong></p>
              <p>Privacy: <strong className="text-foreground">privacy@raimzeal.com</strong></p>
              <p>Website: <a href="https://www.raimzeal.com" className="text-primary">www.raimzeal.com</a></p>
            </div>
          </section>

        </div>
      </div>
      <BottomNav />
    </div>
  );
}
