import { Router, type IRouter } from "express";
import healthRouter from "./health";
import appRouter from "./routes";
import oviaRouter from "./ovia";
import emailRouter from "./email";
import stripeRouter from "./stripe";
import authRouter from "./auth";
import communityRouter from "./community";
import exportRouter from "./export";
import macrosRouter from "./macros";
import deleteAccountRouter from "./deleteAccount";
import sleepRouter from "./sleep";
import publicProfileRouter from "./publicProfile";
import personalRecordsRouter from "./personalRecords";
import exercisesRouter from "./exercises";
import customWorkoutsRouter from "./customWorkouts";
import streakFreezeRouter from "./streakFreeze";
import progressPhotosRouter from "./progressPhotos";
import favouriteFoodsRouter from "./favouriteFoods";
import mealPhotoRouter from "./mealPhoto";
import coachMessagesRouter from "./coachMessages";
import workoutLogsRouter from "./workoutLogs";
import mealLogsRouter from "./mealLogs";
import bodyMeasurementsRouter from "./bodyMeasurements";
import waterIntakeRouter from "./waterIntake";
import scheduledWorkoutsRouter from "./scheduledWorkouts";
import userProfileRouter from "./userProfile";
import enrolledProgramRouter from "./enrolledProgram";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(oviaRouter);
router.use(emailRouter);
router.use(stripeRouter);
router.use(communityRouter);
router.use(exportRouter);
router.use(macrosRouter);
router.use(deleteAccountRouter);
router.use(sleepRouter);
router.use(publicProfileRouter);
router.use(personalRecordsRouter);
router.use(exercisesRouter);
router.use(customWorkoutsRouter);
router.use(streakFreezeRouter);
router.use(progressPhotosRouter);
router.use(favouriteFoodsRouter);
router.use(mealPhotoRouter);
router.use(coachMessagesRouter);
router.use(workoutLogsRouter);
router.use(mealLogsRouter);
router.use(bodyMeasurementsRouter);
router.use(waterIntakeRouter);
router.use(scheduledWorkoutsRouter);
router.use(userProfileRouter);
router.use(enrolledProgramRouter);
router.use(appRouter);

export default router;
